SELECT LOC1.LOCATION_NAME    AS Name,
       LOC2.LOCATION_NAME    AS Area,
       LOC1.LOCATION_ID      AS BuildingId,
       LOC2.LOCATION_ID      AS AreaId,
FROM LOCATION LOC1
JOIN LOCATION LOC2 ON LOC1.PARENT_LOCATION_ID = LOC2.LOCATION_ID
WHERE LOC1.LOCATION_TYPE_ID = 2 -- BUILDING