
SELECT an.ANIMAL_ID_NUMBER AS participantId,
       an.DEATH_DATE AS deathDate,
       an.TERMINATION_REASON_ID as reason,
       COALESCE(MAX(CAST(adt.CHANGE_DATETIME AS TIMESTAMP)), ae.CREATED_DATETIME) AS modified
FROM Animal an
LEFT JOIN AUDIT_TRAIL adt ON an.ANIMAL_ID = substring(PRIMARY_KEY_VALUES, length('ANIMAL_ID = '))
    AND adt.TABLE_NAME = 'ANIMAL' AND adt.COLUMN_NAME = 'death_date'
LEFT JOIN ANIMAL_EVENT ae ON ae.ANIMAL_ID = an.ANIMAL_ID AND EVENT_ID = 1  -- Received
WHERE an.ANIMAL_DISPOSITION_ID = 4 -- died
AND an.TERMINATION_REASON_ID != 10 -- Invalid Id
GROUP BY an.ANIMAL_ID_NUMBER,
    an.DEATH_DATE,
    an.TERMINATION_REASON_ID,
    ae.CREATED_DATETIME