
SELECT ANIMAL_ID_NUMBER AS Id,
       DEATH_DATE AS deathDate,
       TERMINATION_REASON_ID as reason
FROM Animal
WHERE ANIMAL_DISPOSITION_ID = 4 -- died
AND TERMINATION_REASON_ID != 10 -- Invalid Id