
SELECT anm.ANIMAL_ID_NUMBER  AS Id,
       CAST(anmEvt.EVENT_DATETIME AS TIMESTAMP) AS eventDate,
       evt.NAME as destination,
FROM ANIMAL_EVENT anmEvt
LEFT JOIN ANIMAL anm ON anmEvt.ANIMAL_ID = anm.ANIMAL_ID
LEFT JOIN EVENT evt ON anmEvt.EVENT_ID = evt.EVENT_ID
WHERE anmEvt.EVENT_ID IN (SELECT EVENT_ID FROM EVENT WHERE NAME LIKE 'Lab Transfer To%')