SELECT
    PROTOCOL_NUMBER         as Protocol,
    USER_REFERENCE_NUMBER   as UserReferenceNumber,
    SHORT_TITLE             as ShortTitle,
    PI_NAME                 as Investigator,
    PROTOCOL_TYPE           as ProtocolType,
    CURRENT_STATE           as CurrentState,
    SUBMIT_DATE             as SubmitDate,
    APPROVAL_DATE           as ApprovalDate,
    EXPIRATION_DATE         as ExpirationDate,
    EFFECTIVE_DATE          as EffectiveDate,
    RENEWAL_DATE            as RenewalDate,
    AUTHORIZED_AMT          as AuthorizedAmt,
    ON_ORDER_AMT            as OnOrderAmt,
    USED_AMT                as UsedAmt,
    AVAILABLE_AMT           as AvailableAmt,
    PERCENT_LEFT            as PercentLeft,
    SEGMENT_ID              as SegmentId,
FROM PROTOCOL_USAGE_TEMP