SELECT 'PROTOCOL-' || PROTOCOL_ID AS "objectid",
       PROTOCOL_NUMBER AS "title",
       PROTOCOL_NUMBER AS "external_id",
       PROTOCOL_ID AS "protocol",
       DEPARTMENT_ID AS "departmentId",
       PROTOCOL_ID_PREFIX AS "prefix",
       PROTOCOL_ID_SUFFIX AS "suffix",
       PROTOCOL_SHORT_TITLE AS "description",
       APPROVAL_DATE AS "approve",
       EXPIRATION_DATE AS "enddate",
       RENEWAL_DATE AS "renewalDate",
       EMERGENCY_PHONE_NUM AS "emergencyPhoneNumber",
       INACTIVE_DATE AS "inactiveDate",
       NEXT_REVIEW_DATE AS "nextReviewDate",
       LOCATION_ID AS "locationId",
       EFFECTIVE_DATE AS "effectiveDate",
       CURRENT_STATE AS "currentState",
       USER_REFERENCE_NUMBER AS "userReferenceNumber",
       UNRESTRICTED_VIEW_YN AS "isUnrestrictedView",
       AUDIT_YN AS "isAudit",
       AUDIT_YN_MODIFIED_YN AS "isAuditModified",
       PROTOCOL_TYPE_ID AS "protocolTypeId",
       PARENT_PROTOCOL_ID AS "parentProtocolId",
       QUESTIONNAIRE_ID AS "questionnaireId",
       AMENDMENT_REASON AS "amendmentReason",
       REQUESTED_EFFECTIVE_DATE AS "requestedEffectiveDate",
       PROTOCOL_CATEGORY_ID AS "protocolCategoryId",
       OBJECTIVE AS "objective",
       RATIONALE AS "rationale",
       TISSUE_HARVEST_YN AS "isTissueHarvest",
       ORDER_TRACKING_YN AS "isOrderTracking",
       LONG_TERM_YN AS "isLongTerm",
       IN_VIVO_YN AS "isInVivo",
       STOCK_YN AS "isStock",
       SUBMISSION_DATE AS "submissionDate",
       REVIEW_COMPLETION_DATE AS "reviewCompletionDate",
       HONOR_RESET_YN AS "isHonorReset",
       COALESCE(MAX(CAST(adt.CHANGE_DATETIME AS TIMESTAMP)), to_date('01/01/1970' ,'MM/DD/YYYY')) AS modified
FROM PROTOCOL p
LEFT JOIN AUDIT_TRAIL adt ON p.PROTOCOL_ID = substring(PRIMARY_KEY_VALUES, length('PROTOCOL_ID = '))
AND adt.TABLE_NAME = 'PROTOCOL'
WHERE PROTOCOL_NUMBER IS NOT NULL
GROUP BY PROTOCOL_ID,
         PROTOCOL_NUMBER,
         DEPARTMENT_ID,
         PROTOCOL_ID_PREFIX,
         PROTOCOL_ID_SUFFIX,
         PROTOCOL_SHORT_TITLE,
         APPROVAL_DATE,
         EXPIRATION_DATE,
         RENEWAL_DATE,
         EMERGENCY_PHONE_NUM,
         INACTIVE_DATE,
         NEXT_REVIEW_DATE,
         LOCATION_ID,
         EFFECTIVE_DATE,
         CURRENT_STATE,
         USER_REFERENCE_NUMBER,
         UNRESTRICTED_VIEW_YN,
         AUDIT_YN,
         AUDIT_YN_MODIFIED_YN,
         PROTOCOL_TYPE_ID,
         PARENT_PROTOCOL_ID,
         QUESTIONNAIRE_ID,
         AMENDMENT_REASON,
         REQUESTED_EFFECTIVE_DATE,
         PROTOCOL_CATEGORY_ID,
         OBJECTIVE,
         RATIONALE,
         TISSUE_HARVEST_YN,
         ORDER_TRACKING_YN,
         IN_VIVO_YN,
         LONG_TERM_YN,
         STOCK_YN,
         SUBMISSION_DATE,
         REVIEW_COMPLETION_DATE,
         HONOR_RESET_YN
